spring:
  cache:
    #一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
    
  redis:
    host: 192.168.0.10
    port: 6379
    password: Bm2018
    #连接超时时间
    timeout: 6000
    #Redis默认情况下有16个分片，这里配置具体使用的分片
    database : 10
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        #连接池中的最大空闲连接 默认 8
        max-idle: 100
        #连接池中的最小空闲连接 默认 0
        min-idle: 0



