server:
  port: 8080
  servlet:
    context-path: /beetl

    
spring:
  mvc:
    view:
      prefix: /pages
  
  
###################  beetl配置  ###################
beetl:
  #delimiter-statement-start: @   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false
