server:
  port: 80
  servlet:
    context-path: /

spring:
  redis:
    host: r-uf6tknbhr9hzsfyzukpd.redis.rds.aliyuncs.com
    password: LaiTest@2020
    database: 1
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 100
        min-idle: 100  
