server:
  port: 80
  servlet:
    context-path: /
    
spring:
  # mysql配置
  datasource:
    url: jdbc:mysql://192.168.2.166:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    
    
  # redis配置
  redis:
    host: 192.168.2.166
    port: 6379
    password: 123456
    # 连接超时时间
    timeout: 6000
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database : 10
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 100
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
   
  # rabbitmq配置 
  rabbitmq:
    host: 192.168.2.167
    port: 5672
    username: lieping
    password: Lieping@123  
#    virtual-host: /
#    listener:
#      direct:
#        # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
#        acknowledge-mode: manual

# 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
mybatis:
  mapper-locations: classpath:com/yucong/mapping/*.xml

  
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
  
# 开启swagger
swagger:
  enabled: true
  
# 系统环境参数配置    
env:
  verCode: 1.9.0 
  envName: test
  isVerifySign: false
  isAuthLogin: false
  isProduct: true
  isSendMQ: false
  
