server:
  port: 80
  servlet:
    context-path: /chapter11

spring:
  rabbitmq:
    host: localhost
    username: yucong
    password: 123456
    port: 5672
    virtual-host: /
    listener:
      direct:
        # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
        acknowledge-mode: manual



