server:
  port: 81
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mysql://rm-wz936477ppnwe9zamfo.mysql.rds.aliyuncs.com:3306/shiro-web?characterEncoding=utf-8
    username: syp_test
    password: a123456! 

mybatis:
  mapper-locations: classpath:com/yucong/mapper/*.xml


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
  
    
password:
  algorithmName: md5
  hashIterations: 2
  

shiro:
  redis:
    host: 47.96.21.192
    port: 6379
    timeout: 6000
    password: crm2019redis  