# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.2.166:3306/alieping-test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    username: dev
    password: qizhi123
    driver-class-name: com.mysql.jdbc.Driver

    # druid,更多属性可以看官网
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      
      # 配置StatFilter
      filter:
        config:
          enabled: true
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

        # 配置WallFilter
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false





